"""OpenAPI configuration for FetchText Document Processor API.

This module provides rich metadata, tag definitions, and security schemes
for the OpenAPI specification generated by FastAPI.
"""

from typing import Dict, Any, List

# =============================================================================
# API METADATA
# =============================================================================

API_TITLE = "FetchText Document Processor API"
API_VERSION = "1.0.0"
API_DESCRIPTION = """
## Overview

FetchText Document Processor API provides AI-powered document processing,
template matching, and field extraction capabilities.

### Key Features

- **Document Processing**: Upload PDFs, DOCX, images and extract structured data
- **Template Matching**: Automatically match documents to templates or generate new ones
- **Field Extraction**: AI-powered extraction of specific fields with confidence scores
- **Webhooks**: Receive real-time notifications when processing completes

### Authentication

All API endpoints (except health checks) require authentication:

| Auth Type | Use Case | Header Format |
|-----------|----------|---------------|
| **API Key** | Third-party integrations | `Authorization: Bearer ftxt_xxx` |
| **JWT Token** | Dashboard users | `Authorization: Bearer <jwt>` |

### Rate Limits

| Limit Type | Default | Configurable |
|------------|---------|--------------|
| General requests | 60/minute | Yes |
| Upload operations | 10/minute | Yes |

Rate limit headers are included in all responses:
- `X-RateLimit-Limit`: Maximum requests allowed
- `X-RateLimit-Remaining`: Requests remaining in window
- `X-RateLimit-Reset`: Unix timestamp when limit resets

### Base URLs

| Environment | URL |
|-------------|-----|
| Production | `https://api.fetchtext.io` |
| Local Development | `http://localhost:8090` |

### Webhook Support

Configure webhooks to receive real-time notifications when document processing completes.
Webhooks are signed with HMAC-SHA256 for security verification.

### Getting Started

1. [Get your API key](/docs#section/Authentication)
2. [Process your first document](/docs#tag/Third-Party-API-v1/operation/process_document_api_v1_process_post)
3. [Set up webhooks](/docs#section/Webhooks)
"""

API_CONTACT = {
    "name": "FetchText Support",
    "url": "https://fetchtext.io/support",
    "email": "support@fetchtext.io"
}

API_LICENSE = {
    "name": "Proprietary",
    "url": "https://fetchtext.io/terms"
}

API_SERVERS = [
    {
        "url": "https://api.fetchtext.io",
        "description": "Production server"
    },
    {
        "url": "http://localhost:8090",
        "description": "Local development server"
    }
]

# =============================================================================
# TAG DEFINITIONS
# =============================================================================

API_TAGS: List[Dict[str, Any]] = [
    {
        "name": "Third-Party API v1",
        "description": """
External API for third-party integrations.

**Authentication**: API Key (Bearer token starting with `ftxt_`)

**Rate Limits**:
- General requests: 60/minute (configurable)
- Upload operations: 10/minute (configurable)

**Key Endpoints**:
- `POST /api/v1/process` - Process document with template matching
- `GET /api/v1/jobs/{job_id}` - Get job status and results
- `GET /api/v1/templates` - List available templates
        """,
        "externalDocs": {
            "description": "Integration Guide",
            "url": "https://docs.fetchtext.io/quickstart"
        }
    },
    {
        "name": "Documents",
        "description": """
Basic document upload and processing endpoints.

Supports: PDF, DOCX, PPTX, HTML, Markdown, TXT, and common image formats.

**Features**:
- Single document processing
- Batch processing (up to 10 documents)
- Text, metadata, and structure extraction
        """
    },
    {
        "name": "Enhanced Documents",
        "description": """
AI-enhanced document processing with template matching and field extraction.

**Capabilities**:
- Smart template matching with confidence scores
- Auto-template generation from document samples
- Two-pass extraction for improved accuracy
- Field position detection for highlighting
        """
    },
    {
        "name": "Models",
        "description": """
AI provider and model configuration management.

**Supported Providers**:
- **Ollama**: Local CPU-based models (privacy-focused)
- **Azure OpenAI**: Cloud-based GPT models (faster processing)

Switch providers dynamically without restarting the service.
        """
    },
    {
        "name": "Health",
        "description": """
Service health and readiness checks.

**Endpoints**:
- `/health/` - Basic health check
- `/health/ready` - Readiness check (all dependencies available)
- `/health/live` - Liveness check (service running)

No authentication required for health endpoints.
        """
    },
    {
        "name": "API Key Management",
        "description": """
Create and manage API keys for third-party access.

**Authentication**: Requires JWT token (dashboard users only)

**Features**:
- Create keys with custom permissions
- Set expiration and rate limits
- Track usage statistics
- Revoke or delete keys
        """
    },
    {
        "name": "Google Docs",
        "description": """
Google Docs/Drive integration for document import.

**Authentication Methods**:
- OAuth2 (user consent flow)
- Service Account (server-to-server)

Import documents directly from Google Drive without manual download.
        """
    },
    {
        "name": "Email",
        "description": """
Email notification service for organization invitations.

Uses SendGrid for reliable email delivery.
        """
    }
]

# =============================================================================
# SECURITY SCHEMES
# =============================================================================

SECURITY_SCHEMES = {
    # Note: "APIKey" matches the scheme_name in middleware/api_auth.py
    "APIKey": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "API Key",
        "description": """
API Key authentication for third-party integrations.

**Format**: `Authorization: Bearer ftxt_<key>`

**How to obtain**:
1. Log into the FetchText dashboard
2. Go to Settings → API Keys
3. Click "Create New Key"
4. Copy the key (shown only once!)

**Key format**: Keys start with `ftxt_` followed by 43 characters.

**Example**:
```
Authorization: Bearer ftxt_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
```
        """
    },
    "JWTAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": """
JWT Bearer token from Supabase for dashboard users.

Used for admin operations like API key management.

**How to obtain**:
1. Authenticate via the FetchText dashboard
2. JWT token is automatically included in requests

**Token contents**: User ID, email, role, organization membership
        """
    }
}

# =============================================================================
# WEBHOOK DOCUMENTATION
# =============================================================================

WEBHOOK_DESCRIPTION = """
## Webhooks

FetchText can send webhook notifications when document processing completes.

### Setting Up Webhooks

Include `webhook_url` when calling the `/api/v1/process` endpoint:

```bash
curl -X POST https://api.fetchtext.io/api/v1/process \\
  -H "Authorization: Bearer ftxt_your_api_key" \\
  -F "file=@document.pdf" \\
  -F "webhook_url=https://your-app.com/webhooks/fetchtext" \\
  -F "webhook_secret=your_secret_key"
```

### Webhook Payload

```json
{
  "job_id": "abc123-def456-ghi789",
  "status": "completed",
  "result": {
    "template_id": "tpl_001",
    "template_name": "Invoice Template",
    "extracted_data": {
      "vendor_name": {"value": "Acme Corp", "confidence": 0.95},
      "total_amount": {"value": "$1,234.56", "confidence": 0.92}
    },
    "extraction_method": "template_matched"
  },
  "processing_time_ms": 2341,
  "completed_at": "2025-02-04T12:00:02Z"
}
```

### Security: Signature Verification

All webhooks include an `X-Webhook-Signature` header with an HMAC-SHA256 signature.

**Python verification example**:
```python
import hmac
import hashlib

def verify_signature(payload: bytes, signature: str, secret: str) -> bool:
    expected = hmac.new(
        secret.encode(),
        payload,
        hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(f"sha256={expected}", signature)
```

### Retry Policy

| Attempt | Delay |
|---------|-------|
| 1 | Immediate |
| 2 | 1 minute |
| 3 | 5 minutes |
| 4 | 30 minutes |
| 5 | 2 hours |

After 5 failed attempts, the webhook is marked as failed.
"""

# =============================================================================
# ERROR CODES
# =============================================================================

ERROR_CODES_DESCRIPTION = """
## Error Codes

All errors return a JSON response with a `detail` field:

```json
{
  "detail": "Error message describing what went wrong"
}
```

### HTTP Status Codes

| Code | Meaning | Common Causes |
|------|---------|---------------|
| 400 | Bad Request | Invalid input, unsupported file type |
| 401 | Unauthorized | Missing or invalid API key |
| 403 | Forbidden | Insufficient permissions, org access denied |
| 404 | Not Found | Job or resource doesn't exist |
| 429 | Too Many Requests | Rate limit exceeded |
| 500 | Internal Error | Server-side processing error |
| 503 | Unavailable | Database or service unavailable |

### Rate Limit Errors (429)

When rate limited, the response includes:
- `X-RateLimit-Limit`: Your limit
- `X-RateLimit-Remaining`: `0`
- `Retry-After`: Seconds until reset
"""

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_openapi_config() -> Dict[str, Any]:
    """Return OpenAPI configuration dict for FastAPI initialization."""
    return {
        "title": API_TITLE,
        "version": API_VERSION,
        "description": API_DESCRIPTION,
        "contact": API_CONTACT,
        "license_info": API_LICENSE,
        "openapi_tags": API_TAGS
    }


def get_custom_openapi_schema(app) -> Dict[str, Any]:
    """Generate custom OpenAPI schema with additional documentation.

    This function enhances the auto-generated OpenAPI schema with:
    - Custom servers list
    - Security scheme definitions
    - Additional documentation sections

    Args:
        app: FastAPI application instance

    Returns:
        Enhanced OpenAPI schema dictionary
    """
    from fastapi.openapi.utils import get_openapi

    if app.openapi_schema:
        return app.openapi_schema

    openapi_schema = get_openapi(
        title=API_TITLE,
        version=API_VERSION,
        description=API_DESCRIPTION + "\n\n" + WEBHOOK_DESCRIPTION + "\n\n" + ERROR_CODES_DESCRIPTION,
        routes=app.routes,
        tags=API_TAGS,
        contact=API_CONTACT,
        license_info=API_LICENSE
    )

    # Add servers
    openapi_schema["servers"] = API_SERVERS

    # Add security schemes
    openapi_schema["components"] = openapi_schema.get("components", {})
    openapi_schema["components"]["securitySchemes"] = SECURITY_SCHEMES

    app.openapi_schema = openapi_schema
    return app.openapi_schema
