/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkflowTestImport } from './routes/workflow-test'
import { Route as TestStorageDebugImport } from './routes/test-storage-debug'
import { Route as DebugExampleImport } from './routes/debug-example'
import { Route as DebugImport } from './routes/debug'
import { Route as ClerkRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedTemplatesImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedDocumentsImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as errors503Import } from './routes/(errors)/503'
import { Route as errors500Import } from './routes/(errors)/500'
import { Route as errors404Import } from './routes/(errors)/404'
import { Route as errors403Import } from './routes/(errors)/403'
import { Route as errors401Import } from './routes/(errors)/401'
import { Route as authSignupConfirmationImport } from './routes/(auth)/signup-confirmation'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2Import } from './routes/(auth)/sign-in-2'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDocumentsIndexImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedChatsIndexImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAiModelsImport } from './routes/_authenticated/settings/ai-models'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedDocumentsUploadImport } from './routes/_authenticated/documents/upload'
import { Route as AuthenticatedDocumentsProcessDocumentImport } from './routes/_authenticated/documents/process-document'
import { Route as AuthenticatedDocumentsDocumentIdImport } from './routes/_authenticated/documents/$documentId'
import { Route as AuthenticatedWorkflowsInstancesIndexImport } from './routes/_authenticated/workflows/instances/index'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdImport } from './routes/_authenticated/workflows/instances/$instanceId'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdMonitorImport } from './routes/_authenticated/workflows/instances/$instanceId.monitor'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdLogsImport } from './routes/_authenticated/workflows/instances/$instanceId.logs'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdExecutionImport } from './routes/_authenticated/workflows/instances/$instanceId.execution'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdEditorImport } from './routes/_authenticated/workflows/instances/$instanceId.editor'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdConfigurationImport } from './routes/_authenticated/workflows/instances/$instanceId.configuration'

// Create/Update Routes

const WorkflowTestRoute = WorkflowTestImport.update({
  id: '/workflow-test',
  path: '/workflow-test',
  getParentRoute: () => rootRoute,
} as any)

const TestStorageDebugRoute = TestStorageDebugImport.update({
  id: '/test-storage-debug',
  path: '/test-storage-debug',
  getParentRoute: () => rootRoute,
} as any)

const DebugExampleRoute = DebugExampleImport.update({
  id: '/debug-example',
  path: '/debug-example',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const ClerkRouteRoute = ClerkRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTemplatesRoute = AuthenticatedTemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDocumentsRoute = AuthenticatedDocumentsImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503Route = errors503Import.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRoute,
} as any)

const errors500Route = errors500Import.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const errors404Route = errors404Import.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const errors403Route = errors403Import.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const errors401Route = errors401Import.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRoute,
} as any)

const authSignupConfirmationRoute = authSignupConfirmationImport.update({
  id: '/(auth)/signup-confirmation',
  path: '/signup-confirmation',
  getParentRoute: () => rootRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authSignIn2Route = authSignIn2Import.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRoute,
} as any)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)

const ClerkauthRouteRoute = ClerkauthRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)

const ClerkauthSignUpRoute = ClerkauthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)

const ClerkauthSignInRoute = ClerkauthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAiModelsRoute =
  AuthenticatedSettingsAiModelsImport.update({
    id: '/ai-models',
    path: '/ai-models',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedDocumentsUploadRoute =
  AuthenticatedDocumentsUploadImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

const AuthenticatedDocumentsProcessDocumentRoute =
  AuthenticatedDocumentsProcessDocumentImport.update({
    id: '/process-document',
    path: '/process-document',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

const AuthenticatedWorkflowsInstancesIndexRoute =
  AuthenticatedWorkflowsInstancesIndexImport.update({
    id: '/workflows/instances/',
    path: '/workflows/instances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdRoute =
  AuthenticatedWorkflowsInstancesInstanceIdImport.update({
    id: '/workflows/instances/$instanceId',
    path: '/workflows/instances/$instanceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute =
  AuthenticatedWorkflowsInstancesInstanceIdMonitorImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedWorkflowsInstancesInstanceIdRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdLogsRoute =
  AuthenticatedWorkflowsInstancesInstanceIdLogsImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedWorkflowsInstancesInstanceIdRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute =
  AuthenticatedWorkflowsInstancesInstanceIdExecutionImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => AuthenticatedWorkflowsInstancesInstanceIdRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdEditorRoute =
  AuthenticatedWorkflowsInstancesInstanceIdEditorImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedWorkflowsInstancesInstanceIdRoute,
  } as any)

const AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute =
  AuthenticatedWorkflowsInstancesInstanceIdConfigurationImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AuthenticatedWorkflowsInstancesInstanceIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/debug-example': {
      id: '/debug-example'
      path: '/debug-example'
      fullPath: '/debug-example'
      preLoaderRoute: typeof DebugExampleImport
      parentRoute: typeof rootRoute
    }
    '/test-storage-debug': {
      id: '/test-storage-debug'
      path: '/test-storage-debug'
      fullPath: '/test-storage-debug'
      preLoaderRoute: typeof TestStorageDebugImport
      parentRoute: typeof rootRoute
    }
    '/workflow-test': {
      id: '/workflow-test'
      path: '/workflow-test'
      fullPath: '/workflow-test'
      preLoaderRoute: typeof WorkflowTestImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteImport
      parentRoute: typeof ClerkRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteImport
      parentRoute: typeof ClerkRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup-confirmation': {
      id: '/(auth)/signup-confirmation'
      path: '/signup-confirmation'
      fullPath: '/signup-confirmation'
      preLoaderRoute: typeof authSignupConfirmationImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500Import
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdImport
      parentRoute: typeof AuthenticatedDocumentsImport
    }
    '/_authenticated/documents/process-document': {
      id: '/_authenticated/documents/process-document'
      path: '/process-document'
      fullPath: '/documents/process-document'
      preLoaderRoute: typeof AuthenticatedDocumentsProcessDocumentImport
      parentRoute: typeof AuthenticatedDocumentsImport
    }
    '/_authenticated/documents/upload': {
      id: '/_authenticated/documents/upload'
      path: '/upload'
      fullPath: '/documents/upload'
      preLoaderRoute: typeof AuthenticatedDocumentsUploadImport
      parentRoute: typeof AuthenticatedDocumentsImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/ai-models': {
      id: '/_authenticated/settings/ai-models'
      path: '/ai-models'
      fullPath: '/settings/ai-models'
      preLoaderRoute: typeof AuthenticatedSettingsAiModelsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInImport
      parentRoute: typeof ClerkauthRouteImport
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpImport
      parentRoute: typeof ClerkauthRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementImport
      parentRoute: typeof ClerkAuthenticatedRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexImport
      parentRoute: typeof AuthenticatedDocumentsImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows/instances/$instanceId': {
      id: '/_authenticated/workflows/instances/$instanceId'
      path: '/workflows/instances/$instanceId'
      fullPath: '/workflows/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows/instances/': {
      id: '/_authenticated/workflows/instances/'
      path: '/workflows/instances'
      fullPath: '/workflows/instances'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows/instances/$instanceId/configuration': {
      id: '/_authenticated/workflows/instances/$instanceId/configuration'
      path: '/configuration'
      fullPath: '/workflows/instances/$instanceId/configuration'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdConfigurationImport
      parentRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
    }
    '/_authenticated/workflows/instances/$instanceId/editor': {
      id: '/_authenticated/workflows/instances/$instanceId/editor'
      path: '/editor'
      fullPath: '/workflows/instances/$instanceId/editor'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdEditorImport
      parentRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
    }
    '/_authenticated/workflows/instances/$instanceId/execution': {
      id: '/_authenticated/workflows/instances/$instanceId/execution'
      path: '/execution'
      fullPath: '/workflows/instances/$instanceId/execution'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdExecutionImport
      parentRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
    }
    '/_authenticated/workflows/instances/$instanceId/logs': {
      id: '/_authenticated/workflows/instances/$instanceId/logs'
      path: '/logs'
      fullPath: '/workflows/instances/$instanceId/logs'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdLogsImport
      parentRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
    }
    '/_authenticated/workflows/instances/$instanceId/monitor': {
      id: '/_authenticated/workflows/instances/$instanceId/monitor'
      path: '/monitor'
      fullPath: '/workflows/instances/$instanceId/monitor'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdMonitorImport
      parentRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAiModelsRoute: typeof AuthenticatedSettingsAiModelsRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAiModelsRoute: AuthenticatedSettingsAiModelsRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedDocumentsProcessDocumentRoute: typeof AuthenticatedDocumentsProcessDocumentRoute
  AuthenticatedDocumentsUploadRoute: typeof AuthenticatedDocumentsUploadRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsDocumentIdRoute:
      AuthenticatedDocumentsDocumentIdRoute,
    AuthenticatedDocumentsProcessDocumentRoute:
      AuthenticatedDocumentsProcessDocumentRoute,
    AuthenticatedDocumentsUploadRoute: AuthenticatedDocumentsUploadRoute,
    AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedWorkflowsInstancesInstanceIdRouteChildren {
  AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute
  AuthenticatedWorkflowsInstancesInstanceIdEditorRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdEditorRoute
  AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute
  AuthenticatedWorkflowsInstancesInstanceIdLogsRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdLogsRoute
  AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute
}

const AuthenticatedWorkflowsInstancesInstanceIdRouteChildren: AuthenticatedWorkflowsInstancesInstanceIdRouteChildren =
  {
    AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute:
      AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute,
    AuthenticatedWorkflowsInstancesInstanceIdEditorRoute:
      AuthenticatedWorkflowsInstancesInstanceIdEditorRoute,
    AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute:
      AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute,
    AuthenticatedWorkflowsInstancesInstanceIdLogsRoute:
      AuthenticatedWorkflowsInstancesInstanceIdLogsRoute,
    AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute:
      AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute,
  }

const AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren =
  AuthenticatedWorkflowsInstancesInstanceIdRoute._addFileChildren(
    AuthenticatedWorkflowsInstancesInstanceIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkflowsInstancesInstanceIdRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren
  AuthenticatedWorkflowsInstancesIndexRoute: typeof AuthenticatedWorkflowsInstancesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkflowsInstancesInstanceIdRoute:
    AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren,
  AuthenticatedWorkflowsInstancesIndexRoute:
    AuthenticatedWorkflowsInstancesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/debug-example': typeof DebugExampleRoute
  '/test-storage-debug': typeof TestStorageDebugRoute
  '/workflow-test': typeof WorkflowTestRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/signup-confirmation': typeof authSignupConfirmationRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/process-document': typeof AuthenticatedDocumentsProcessDocumentRoute
  '/documents/upload': typeof AuthenticatedDocumentsUploadRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai-models': typeof AuthenticatedSettingsAiModelsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren
  '/workflows/instances': typeof AuthenticatedWorkflowsInstancesIndexRoute
  '/workflows/instances/$instanceId/configuration': typeof AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute
  '/workflows/instances/$instanceId/editor': typeof AuthenticatedWorkflowsInstancesInstanceIdEditorRoute
  '/workflows/instances/$instanceId/execution': typeof AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute
  '/workflows/instances/$instanceId/logs': typeof AuthenticatedWorkflowsInstancesInstanceIdLogsRoute
  '/workflows/instances/$instanceId/monitor': typeof AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/debug-example': typeof DebugExampleRoute
  '/test-storage-debug': typeof TestStorageDebugRoute
  '/workflow-test': typeof WorkflowTestRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/signup-confirmation': typeof authSignupConfirmationRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/documents/process-document': typeof AuthenticatedDocumentsProcessDocumentRoute
  '/documents/upload': typeof AuthenticatedDocumentsUploadRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/ai-models': typeof AuthenticatedSettingsAiModelsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren
  '/workflows/instances': typeof AuthenticatedWorkflowsInstancesIndexRoute
  '/workflows/instances/$instanceId/configuration': typeof AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute
  '/workflows/instances/$instanceId/editor': typeof AuthenticatedWorkflowsInstancesInstanceIdEditorRoute
  '/workflows/instances/$instanceId/execution': typeof AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute
  '/workflows/instances/$instanceId/logs': typeof AuthenticatedWorkflowsInstancesInstanceIdLogsRoute
  '/workflows/instances/$instanceId/monitor': typeof AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/debug': typeof DebugRoute
  '/debug-example': typeof DebugExampleRoute
  '/test-storage-debug': typeof TestStorageDebugRoute
  '/workflow-test': typeof WorkflowTestRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/signup-confirmation': typeof authSignupConfirmationRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/documents/process-document': typeof AuthenticatedDocumentsProcessDocumentRoute
  '/_authenticated/documents/upload': typeof AuthenticatedDocumentsUploadRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/ai-models': typeof AuthenticatedSettingsAiModelsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRouteWithChildren
  '/_authenticated/workflows/instances/': typeof AuthenticatedWorkflowsInstancesIndexRoute
  '/_authenticated/workflows/instances/$instanceId/configuration': typeof AuthenticatedWorkflowsInstancesInstanceIdConfigurationRoute
  '/_authenticated/workflows/instances/$instanceId/editor': typeof AuthenticatedWorkflowsInstancesInstanceIdEditorRoute
  '/_authenticated/workflows/instances/$instanceId/execution': typeof AuthenticatedWorkflowsInstancesInstanceIdExecutionRoute
  '/_authenticated/workflows/instances/$instanceId/logs': typeof AuthenticatedWorkflowsInstancesInstanceIdLogsRoute
  '/_authenticated/workflows/instances/$instanceId/monitor': typeof AuthenticatedWorkflowsInstancesInstanceIdMonitorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/clerk'
    | '/debug'
    | '/debug-example'
    | '/test-storage-debug'
    | '/workflow-test'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/signup-confirmation'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/documents'
    | '/templates'
    | '/documents/$documentId'
    | '/documents/process-document'
    | '/documents/upload'
    | '/settings/account'
    | '/settings/ai-models'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/documents/'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/workflows/instances/$instanceId'
    | '/workflows/instances'
    | '/workflows/instances/$instanceId/configuration'
    | '/workflows/instances/$instanceId/editor'
    | '/workflows/instances/$instanceId/execution'
    | '/workflows/instances/$instanceId/logs'
    | '/workflows/instances/$instanceId/monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/debug'
    | '/debug-example'
    | '/test-storage-debug'
    | '/workflow-test'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/signup-confirmation'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/templates'
    | '/documents/$documentId'
    | '/documents/process-document'
    | '/documents/upload'
    | '/settings/account'
    | '/settings/ai-models'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/documents'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/workflows/instances/$instanceId'
    | '/workflows/instances'
    | '/workflows/instances/$instanceId/configuration'
    | '/workflows/instances/$instanceId/editor'
    | '/workflows/instances/$instanceId/execution'
    | '/workflows/instances/$instanceId/logs'
    | '/workflows/instances/$instanceId/monitor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/clerk'
    | '/debug'
    | '/debug-example'
    | '/test-storage-debug'
    | '/workflow-test'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/signup-confirmation'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/templates'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/documents/process-document'
    | '/_authenticated/documents/upload'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/ai-models'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/documents/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/workflows/instances/$instanceId'
    | '/_authenticated/workflows/instances/'
    | '/_authenticated/workflows/instances/$instanceId/configuration'
    | '/_authenticated/workflows/instances/$instanceId/editor'
    | '/_authenticated/workflows/instances/$instanceId/execution'
    | '/_authenticated/workflows/instances/$instanceId/logs'
    | '/_authenticated/workflows/instances/$instanceId/monitor'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  DebugRoute: typeof DebugRoute
  DebugExampleRoute: typeof DebugExampleRoute
  TestStorageDebugRoute: typeof TestStorageDebugRoute
  WorkflowTestRoute: typeof WorkflowTestRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authSignupConfirmationRoute: typeof authSignupConfirmationRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  DebugRoute: DebugRoute,
  DebugExampleRoute: DebugExampleRoute,
  TestStorageDebugRoute: TestStorageDebugRoute,
  WorkflowTestRoute: WorkflowTestRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authSignupConfirmationRoute: authSignupConfirmationRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/clerk",
        "/debug",
        "/debug-example",
        "/test-storage-debug",
        "/workflow-test",
        "/(auth)/forgot-password",
        "/(auth)/otp",
        "/(auth)/reset-password",
        "/(auth)/sign-in",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(auth)/signup-confirmation",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/dashboard",
        "/_authenticated/documents",
        "/_authenticated/templates",
        "/_authenticated/apps/",
        "/_authenticated/chats/",
        "/_authenticated/help-center/",
        "/_authenticated/tasks/",
        "/_authenticated/users/",
        "/_authenticated/workflows/instances/$instanceId",
        "/_authenticated/workflows/instances/"
      ]
    },
    "/clerk": {
      "filePath": "clerk/route.tsx",
      "children": [
        "/clerk/(auth)",
        "/clerk/_authenticated"
      ]
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/debug-example": {
      "filePath": "debug-example.tsx"
    },
    "/test-storage-debug": {
      "filePath": "test-storage-debug.tsx"
    },
    "/workflow-test": {
      "filePath": "workflow-test.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/ai-models",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/clerk/(auth)": {
      "filePath": "clerk/(auth)/route.tsx",
      "parent": "/clerk",
      "children": [
        "/clerk/(auth)/sign-in",
        "/clerk/(auth)/sign-up"
      ]
    },
    "/clerk/_authenticated": {
      "filePath": "clerk/_authenticated/route.tsx",
      "parent": "/clerk",
      "children": [
        "/clerk/_authenticated/user-management"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/(auth)/signup-confirmation": {
      "filePath": "(auth)/signup-confirmation.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.tsx"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/documents": {
      "filePath": "_authenticated/documents.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/documents/$documentId",
        "/_authenticated/documents/process-document",
        "/_authenticated/documents/upload",
        "/_authenticated/documents/"
      ]
    },
    "/_authenticated/templates": {
      "filePath": "_authenticated/templates.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/documents/$documentId": {
      "filePath": "_authenticated/documents/$documentId.tsx",
      "parent": "/_authenticated/documents"
    },
    "/_authenticated/documents/process-document": {
      "filePath": "_authenticated/documents/process-document.tsx",
      "parent": "/_authenticated/documents"
    },
    "/_authenticated/documents/upload": {
      "filePath": "_authenticated/documents/upload.tsx",
      "parent": "/_authenticated/documents"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/ai-models": {
      "filePath": "_authenticated/settings/ai-models.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/clerk/(auth)/sign-in": {
      "filePath": "clerk/(auth)/sign-in.tsx",
      "parent": "/clerk/(auth)"
    },
    "/clerk/(auth)/sign-up": {
      "filePath": "clerk/(auth)/sign-up.tsx",
      "parent": "/clerk/(auth)"
    },
    "/clerk/_authenticated/user-management": {
      "filePath": "clerk/_authenticated/user-management.tsx",
      "parent": "/clerk/_authenticated"
    },
    "/_authenticated/apps/": {
      "filePath": "_authenticated/apps/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/documents/": {
      "filePath": "_authenticated/documents/index.tsx",
      "parent": "/_authenticated/documents"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/tasks/": {
      "filePath": "_authenticated/tasks/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/workflows/instances/$instanceId": {
      "filePath": "_authenticated/workflows/instances/$instanceId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/workflows/instances/$instanceId/configuration",
        "/_authenticated/workflows/instances/$instanceId/editor",
        "/_authenticated/workflows/instances/$instanceId/execution",
        "/_authenticated/workflows/instances/$instanceId/logs",
        "/_authenticated/workflows/instances/$instanceId/monitor"
      ]
    },
    "/_authenticated/workflows/instances/": {
      "filePath": "_authenticated/workflows/instances/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/workflows/instances/$instanceId/configuration": {
      "filePath": "_authenticated/workflows/instances/$instanceId.configuration.tsx",
      "parent": "/_authenticated/workflows/instances/$instanceId"
    },
    "/_authenticated/workflows/instances/$instanceId/editor": {
      "filePath": "_authenticated/workflows/instances/$instanceId.editor.tsx",
      "parent": "/_authenticated/workflows/instances/$instanceId"
    },
    "/_authenticated/workflows/instances/$instanceId/execution": {
      "filePath": "_authenticated/workflows/instances/$instanceId.execution.tsx",
      "parent": "/_authenticated/workflows/instances/$instanceId"
    },
    "/_authenticated/workflows/instances/$instanceId/logs": {
      "filePath": "_authenticated/workflows/instances/$instanceId.logs.tsx",
      "parent": "/_authenticated/workflows/instances/$instanceId"
    },
    "/_authenticated/workflows/instances/$instanceId/monitor": {
      "filePath": "_authenticated/workflows/instances/$instanceId.monitor.tsx",
      "parent": "/_authenticated/workflows/instances/$instanceId"
    }
  }
}
ROUTE_MANIFEST_END */
